apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exstasia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mihxjlo/exstasia-backend:24046464426db10cb0ed7e5930f238918becb578
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: uploads
              mountPath: /uploads
          readinessProbe:
            httpGet:
              path: /api/galleries
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/galleries
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: backend-uploads
