apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exstasia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mihxjlo/exstasia-frontend:f718d3b17c75797798bd70a2661ea51f17f478f8
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-configmap
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
